version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    working_dir: /app
    command: python code/app.py
    volumes:
      - ./persistent_data.json:/app/code/persistent_data.json
